export interface MenuItem {
  id: string
  name: string
  price: number
  description: string
  image: string
  isVeg: boolean
  isBestseller?: boolean
}

export interface Restaurant {
  id: string
  name: string
  city: string
  cuisine: string[]
  rating: number
  deliveryTime: string
  priceRange: string
  image: string
  featured?: boolean
  menuItems: MenuItem[]
}

export const cities = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"]

export const cuisineTypes = [
  "All",
  "North Indian",
  "South Indian",
  "Chinese",
  "Italian",
  "Fast Food",
  "Biryani",
  "Pizza",
  "Desserts",
  "Street Food",
]

export const restaurants: Restaurant[] = [
  // Mumbai Restaurants
  {
    id: "1",
    name: "Spice Garden",
    city: "Mumbai",
    cuisine: ["North Indian", "Biryani"],
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/indian-restaurant-with-warm-lighting-and-tradition.jpg",
    featured: true,
    menuItems: [
      {
        id: "m1",
        name: "Butter Chicken",
        price: 320,
        description: "Creamy tomato-based curry with tender chicken",
        image: "/butter-chicken-curry.png",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m2",
        name: "Dal Makhani",
        price: 220,
        description: "Slow-cooked black lentils in rich cream",
        image: "/dal-makhani-lentils.jpg",
        isVeg: true,
      },
      {
        id: "m3",
        name: "Chicken Biryani",
        price: 280,
        description: "Fragrant basmati rice with spiced chicken",
        image: "/chicken-biryani-rice.jpg",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m4",
        name: "Paneer Tikka",
        price: 240,
        description: "Grilled cottage cheese with spices",
        image: "/paneer-tikka-skewers.jpg",
        isVeg: true,
      },
    ],
  },
  {
    id: "2",
    name: "Wok & Roll",
    city: "Mumbai",
    cuisine: ["Chinese", "Fast Food"],
    rating: 4.2,
    deliveryTime: "25-30 min",
    priceRange: "₹",
    image: "/modern-chinese-restaurant-with-neon-lights.jpg",
    menuItems: [
      {
        id: "m5",
        name: "Hakka Noodles",
        price: 180,
        description: "Stir-fried noodles with vegetables",
        image: "/hakka-noodles.png",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m6",
        name: "Chilli Chicken",
        price: 260,
        description: "Crispy chicken in spicy sauce",
        image: "/chilli-chicken.jpg",
        isVeg: false,
      },
      {
        id: "m7",
        name: "Manchurian",
        price: 200,
        description: "Deep-fried veggie balls in tangy sauce",
        image: "/veg-manchurian.png",
        isVeg: true,
      },
    ],
  },
  // Delhi Restaurants
  {
    id: "3",
    name: "Karim's Legacy",
    city: "Delhi",
    cuisine: ["North Indian", "Biryani"],
    rating: 4.7,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/traditional-mughlai-restaurant-interior.jpg",
    featured: true,
    menuItems: [
      {
        id: "m8",
        name: "Mutton Korma",
        price: 420,
        description: "Rich mutton curry with aromatic spices",
        image: "/mutton-korma-curry.jpg",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m9",
        name: "Seekh Kebab",
        price: 340,
        description: "Minced meat skewers grilled to perfection",
        image: "/seekh-kebab.jpg",
        isVeg: false,
      },
      {
        id: "m10",
        name: "Naan Basket",
        price: 120,
        description: "Assorted freshly baked breads",
        image: "/naan-bread-basket.jpg",
        isVeg: true,
      },
    ],
  },
  {
    id: "4",
    name: "Pizza Paradise",
    city: "Delhi",
    cuisine: ["Italian", "Pizza"],
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/cozy-italian-pizzeria-with-wood-fired-oven.jpg",
    menuItems: [
      {
        id: "m11",
        name: "Margherita Pizza",
        price: 280,
        description: "Classic tomato and mozzarella",
        image: "/margherita-pizza.png",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m12",
        name: "Pepperoni Pizza",
        price: 380,
        description: "Loaded with spicy pepperoni",
        image: "/pepperoni-pizza.png",
        isVeg: false,
      },
      {
        id: "m13",
        name: "Garlic Bread",
        price: 140,
        description: "Crispy bread with garlic butter",
        image: "/garlic-bread.png",
        isVeg: true,
      },
    ],
  },
  // Bangalore Restaurants
  {
    id: "5",
    name: "MTR Classic",
    city: "Bangalore",
    cuisine: ["South Indian"],
    rating: 4.6,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/traditional-south-indian-restaurant-with-banana-le.jpg",
    featured: true,
    menuItems: [
      {
        id: "m14",
        name: "Masala Dosa",
        price: 120,
        description: "Crispy crepe with spiced potato filling",
        image: "/masala-dosa.png",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m15",
        name: "Idli Sambar",
        price: 80,
        description: "Steamed rice cakes with lentil soup",
        image: "/idli-sambar.png",
        isVeg: true,
      },
      {
        id: "m16",
        name: "Filter Coffee",
        price: 40,
        description: "Traditional South Indian coffee",
        image: "/south-indian-filter-coffee.jpg",
        isVeg: true,
      },
    ],
  },
  {
    id: "6",
    name: "Bowl Company",
    city: "Bangalore",
    cuisine: ["Fast Food", "Chinese"],
    rating: 4.1,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/modern-fast-food-restaurant-with-colorful-bowls.jpg",
    menuItems: [
      {
        id: "m17",
        name: "Teriyaki Bowl",
        price: 240,
        description: "Rice bowl with teriyaki chicken",
        image: "/teriyaki-chicken-bowl.jpg",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m18",
        name: "Veg Buddha Bowl",
        price: 200,
        description: "Healthy mixed vegetables with quinoa",
        image: "/buddha-bowl-vegetables.jpg",
        isVeg: true,
      },
    ],
  },
  // Hyderabad Restaurants
  {
    id: "7",
    name: "Paradise Biryani",
    city: "Hyderabad",
    cuisine: ["Biryani", "North Indian"],
    rating: 4.8,
    deliveryTime: "35-45 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    menuItems: [
      {
        id: "m19",
        name: "Hyderabadi Dum Biryani",
        price: 320,
        description: "Authentic slow-cooked biryani",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m20",
        name: "Mirchi Ka Salan",
        price: 180,
        description: "Spicy peanut-sesame curry",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
      {
        id: "m21",
        name: "Double Ka Meetha",
        price: 120,
        description: "Bread pudding dessert",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  {
    id: "8",
    name: "Street Bites",
    city: "Hyderabad",
    cuisine: ["Street Food", "Fast Food"],
    rating: 4.0,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m22",
        name: "Pani Puri",
        price: 60,
        description: "Crispy puris with tangy water",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m23",
        name: "Dahi Puri",
        price: 80,
        description: "Puris topped with curd and chutneys",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  // Chennai Restaurants
  {
    id: "9",
    name: "Saravana Bhavan",
    city: "Chennai",
    cuisine: ["South Indian"],
    rating: 4.4,
    deliveryTime: "25-30 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m24",
        name: "Thali Meals",
        price: 180,
        description: "Complete South Indian meal",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m25",
        name: "Rava Dosa",
        price: 100,
        description: "Crispy semolina crepe",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  {
    id: "10",
    name: "Cream Stone",
    city: "Chennai",
    cuisine: ["Desserts"],
    rating: 4.3,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m26",
        name: "Brownie Sundae",
        price: 220,
        description: "Warm brownie with ice cream",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m27",
        name: "Mango Shake",
        price: 140,
        description: "Fresh mango milkshake",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  // Kolkata Restaurants
  {
    id: "11",
    name: "Oh! Calcutta",
    city: "Kolkata",
    cuisine: ["North Indian", "Street Food"],
    rating: 4.5,
    deliveryTime: "30-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    menuItems: [
      {
        id: "m28",
        name: "Kosha Mangsho",
        price: 380,
        description: "Slow-cooked Bengali mutton curry",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m29",
        name: "Luchi Aloo Dom",
        price: 160,
        description: "Fried bread with potato curry",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  {
    id: "12",
    name: "Arsalan",
    city: "Kolkata",
    cuisine: ["Biryani", "North Indian"],
    rating: 4.6,
    deliveryTime: "35-45 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m30",
        name: "Kolkata Biryani",
        price: 300,
        description: "Light biryani with potato and egg",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m31",
        name: "Rezala",
        price: 340,
        description: "Creamy white mutton curry",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: false,
      },
    ],
  },
  // Pune Restaurants
  {
    id: "13",
    name: "Vaishali",
    city: "Pune",
    cuisine: ["South Indian", "Fast Food"],
    rating: 4.4,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m32",
        name: "Misal Pav",
        price: 100,
        description: "Spicy sprouts curry with bread",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m33",
        name: "Poha",
        price: 60,
        description: "Flattened rice breakfast",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  {
    id: "14",
    name: "Mainland China",
    city: "Pune",
    cuisine: ["Chinese"],
    rating: 4.2,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m34",
        name: "Kung Pao Chicken",
        price: 380,
        description: "Spicy chicken with peanuts",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: false,
        isBestseller: true,
      },
      {
        id: "m35",
        name: "Dim Sum Platter",
        price: 420,
        description: "Assorted steamed dumplings",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: false,
      },
    ],
  },
  // Ahmedabad Restaurants
  {
    id: "15",
    name: "Gordhan Thal",
    city: "Ahmedabad",
    cuisine: ["North Indian", "Street Food"],
    rating: 4.5,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m36",
        name: "Gujarati Thali",
        price: 350,
        description: "Complete Gujarati meal experience",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m37",
        name: "Dhokla",
        price: 80,
        description: "Steamed savory cake",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
  {
    id: "16",
    name: "Havmor",
    city: "Ahmedabad",
    cuisine: ["Desserts", "Fast Food"],
    rating: 4.3,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        id: "m38",
        name: "Cassata Ice Cream",
        price: 160,
        description: "Layered fruit ice cream",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
        isBestseller: true,
      },
      {
        id: "m39",
        name: "Falooda",
        price: 140,
        description: "Rose milk dessert with vermicelli",
        image: "/placeholder.svg?height=100&width=100",
        isVeg: true,
      },
    ],
  },
]
